FROM node:20.12.2
WORKDIR /root

# Копируем package.json
COPY app/package*.json ./
# Устанавливаем ВСЕ зависимости для тестов!
RUN npm ci

# Фикс прав
RUN chmod -R 777 /root

COPY app/ .

CMD ["make", "test"]

