FROM node:20.12.2
WORKDIR /root

# Копируем с правами
COPY --chown=root:root app/package*.json ./
RUN npm ci --only=production

# Фикс прав ДЛЯ SQLite
RUN chmod -R 777 /root

COPY --chown=root:root app/ .

CMD ["make", "test"]
