version: "3.9"
services:
  app:
    image: voitov/devops-for-developers-project-74:latest
    container_name: app-1
    expose:
      - "8080"
    networks:
      - devnet
    depends_on:
      db:
        condition: service_healthy  # Ждет healthy БД

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:          # ← Явно передаем в контейнер (лучше чем env_file)
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: .env        # Дополнительно (опционально)
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      # ↑ ${POSTGRES_USER} подставляется из .env автоматически!
  webserver:
    image: caddy:2.6-alpine
    container_name: webserver-1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
    networks:
      - devnet

networks:
  devnet:

volumes:
  postgres_data: 
